/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TvShowsLazyImport = createFileRoute('/tv-shows')()
const MoviesLazyImport = createFileRoute('/movies')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TvShowsLazyRoute = TvShowsLazyImport.update({
  id: '/tv-shows',
  path: '/tv-shows',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/tv-shows.lazy').then((d) => d.Route))

const MoviesLazyRoute = MoviesLazyImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/movies.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesLazyImport
      parentRoute: typeof rootRoute
    }
    '/tv-shows': {
      id: '/tv-shows'
      path: '/tv-shows'
      fullPath: '/tv-shows'
      preLoaderRoute: typeof TvShowsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/movies': typeof MoviesLazyRoute
  '/tv-shows': typeof TvShowsLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/movies': typeof MoviesLazyRoute
  '/tv-shows': typeof TvShowsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/movies': typeof MoviesLazyRoute
  '/tv-shows': typeof TvShowsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/movies' | '/tv-shows'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/movies' | '/tv-shows'
  id: '__root__' | '/' | '/movies' | '/tv-shows'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  MoviesLazyRoute: typeof MoviesLazyRoute
  TvShowsLazyRoute: typeof TvShowsLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  MoviesLazyRoute: MoviesLazyRoute,
  TvShowsLazyRoute: TvShowsLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/movies",
        "/tv-shows"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/movies": {
      "filePath": "movies.lazy.tsx"
    },
    "/tv-shows": {
      "filePath": "tv-shows.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
